# Generated by Django 5.0.6 on 2026-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=100)),
                ('diameter_mm', models.PositiveIntegerField()),
                ('wall_thickness_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_pressure_bar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_per_meter', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valve_type', models.CharField(max_length=100)),
                ('diameter_mm', models.PositiveIntegerField()),
                ('max_pressure_bar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
